from django import template

register = template.Library()

FR_DICT = {
	'Paj akèy':'Page d\'accueil',
	"Akèy":"Accueil",
	'Sali':'Salut',
	'Jou':"Jours",
	"Istwa nou":"Notre histoire",
	'Nimewo':"Numéro",
	"Non konplè":"Nom complet",
	'Imel':"Imel",
	'Voye li ale':"Envoyer",
	"Ki jou":"Quel jour",
	'Lokalize':'Localiser',
	"Imel":"Email",
	'Sèks':"Sexe",
	"Ki pati":"Catégorie",
	'Doktè':"Docteurs",
	'Pran yon randevou':"Prendre un rendez-vous",
	'Sant disponib':"Centres disponibles",
	'Kontak':"Contact",
	'Ban nou yon apèl':"Appelez-nous",
	'Voye yon mesaj ban nou':"Nous envoyez un mail",
	'Vizite nou':"Visitez-nous",
	"Ou vle fè pitit":"Enfanter",
	"Konfime modpas":"Confirmez le mot de passe",
	'Non':'Prénom',
	"Siyati":"Nom",
	'Dat ou fèt':"Date de naissance",
	'Jwenn yon lopital':"Trouver un hopital",
	"Gwosès":"Grossesse",
	'Tout dwa rezève':"Tous droits reservés",
	"Sonje'm":"Se souvenir de moi",
	"Bliye modpas":"Mot de passe oublié",
	"Konekte":"Connexion",
	"Dekonekte":"Déconnexion",
	'Èd':'Aide',
	'Bonjou':"Bonjour",
	"Bonswa":"Salut",
	"Konnen plis":"En savoir plus",
	'Ou vle fè timoun':'Enfanter',
	'Gwosès avan lè':"Grossesse prématurée",
	'Kontrasepsyon':'Contraception',
	'Sant pou ede':"Centre d'aide",
	"Kelke doktè":"Des médecins",
	"Rele sant ki pi pre a":"Appel d'urgence",
	'Gade nan kat':"Vue dans la carte",
	'Liste yo pito':"Lister les adresses",
	"Chache":"Lancer",
	"Konekte":"Se connecter",
	"Ou pa gen kont":"Pas de compte",
	"Enskri":"S'inscrire",
	"Istwa nou":"A propos de nous",
	"Koneksyon":"Connexion",
	"Si ou pa ko gen kont":"Si vous n'avez pas de compte",
	"Fèmen":"Fermer",
	"Ou gen yon kont deja":"Vous avez un compte",
	'Enskripsyon':"S'inscrire",
	'Ki sik ou':"Votre cycle",
	"Sèks ou":"Votre sexe",
	"Non ou konplè":"Votre nom complet",
	"Modpas":"mot de passe",
	"Konfime modpas la":"Confirmez le mot de passe",
	"Non itilize":"Nom d'utilisateur",
	"Mwen vle fè pitit":"Je veux enfanter",

}
EN_DICT = {
	'Akey':'Home',
	'Akey ':"Overview",
	'Sali':'Hi',
	'Byenvini':'Welcome',
	'Enprime':'Print',
	'Kreye lekol':"Create school",
	'Kreye yon lekol':"Create a school",
	"Gen laboratwa enfomatik":"Computer lab",
	"Si lekol la gen paj sosyal":"Social pages of the school",
	"Omwen telefon ou imel":"Email or phone required",
	"Chache saw vle a":"Search",
	"Pa gen lekol":'No schools',
	"Konfigire kont mwen":'Settings',
	"Gen aksè entènèt":"Internet access",
	'Dekonekte':'Log out',
	'Pwofil mwen':"Profile",
	'Lekol map travay':'Schools',
	"Enskri":"Signup",
	"Pi gwo kapasite pou imaj la":"Size of file less than",
	'Anrejistre':"Save",
	"Directeur":"Director",
	"Chwazi yon logo":"Upload your logo image",
	"Tanpri tape sèlman chif":"Please, enter only number",
	"Tanpri tape yon Kòd valid":"Please, enter a valid ID Code",
	'Konekte':"Log in",
	'Pwofese':"Teacher",
	'Sal':"Classroom",
	'Chan obligatwa':'Required field',
	'Tounen nan etap avan':'Previous step',
	'Pase a etap swivan':'Next step',
	'Prof':'Teacher',
	'Si\'w pa ko manm':"Don't have an account yet ?",
	'chan anplis':'Field(s)',
	'Matye klas sa se':"Materials of this grade are",
	'Koneksyon':"Log in",
	"Janvye":'January',
	"Retire matyè sa":'Delete this',
	"Modifye":"Edit",
	"Eske ou vle efase lekol sa":"Do you want to delete this school",
	"Chan sa obligatwa":"Field required",
	"Seleksyone tout":"Select all",
	"Siw poko pare pou ranpli etap sa":"If you are not ready,do it later",
	'Aplike pita':"I'll do it later",
	"Anrejistre chak elev avek kontak paran":"Enroll each student with their contacts parents",
	'Fevriye':"February",
	'Ajoute':"Add",
	'Seleksyone ane ke lekol la genyen e konbyen sal':"Select grade of the school and how many classroom",
	'Mas':"March",
	'Mwen ap fe sa pita':"Do it later",
	'Dat nesans':"Birthday",
	'Imel paran':'Email of parents',
	'12 janvye':"January 12th",
	"Kreye yon lòt":"Create school",
	"Lis lekol ke'w pa ko fin kreye":"List of uncomplete school registration",
	"Créée":"Created",
	"Kontinye modifikasyon yo":"Move on the latest edit",
	'Efase lekol sa':"Delete this school",
	"Cin ou nif ":"National ID number",
	"Wol adminstratè a":"Administrator status",
	"Retounen nan etap avan":"Previous step",

	'8 mas':"February 8th",
	"Mwen ap antre la":"Get in",
	"Kite sa":"Cancel",
	'Mwayen jeneral':"Global average",
	'Total jeneral':"Total",
	'Admi avek mansyon':"Admis avec mention",
	'Travay byen nan':"is very good in",
	'Diksyone':'Dictionnary',
	"Kou dey sou bilten":"View report",
	"Kou dey sou pefomans":'View performance',
	'We panelis':"School Registration",
	"Vizite lekol la":"Visit the school",
	'Tradwi paj la an':'Translate page in',
	'Chache lekol poum enskri timoun mwen an':'Find a school for my child',
	'Chache yon lekol avèk non an, depatman oubyen non direktè a':'Search school with name, city or name of director',
	'Koman nou fonksyone':'Our work',
	'Kote nou lokalize':'Our place',
	'Kiyes nou ye':'About us',
	'Trebyen':'Very good',
	"Byen":"Good",
	"Pwofese ki sal":"Teacher of what grade",
	'Passab':"Poor",
	"Modifikasyon Direktè":"Editing of",
	"Nivo ke lekol la genyen":"Grade of the school",
	"élèves":"Students",
	"élève":"Student",
	"Anrejistre e pase a etap aprè":"Save and go to next step",
	'Klike e skane sa pou kolekte tout enfomasyon sou':"Click an scan this QRCode for full informations about this student",
	"Medyok":"Very bad",
	'Anrejistre lekol mwen an la':'Include my school',
	"Kontakte'n":'Contact us',
	'Swiv nou':'Follow us',
	'Groupe A':"A Group",
	"Groupe B":"B Group",
	'Mwayen':'Average',
	"Bay paran timoun ki pa la jodi a":'To all parents of absent students',
	'Nimewo':"number",
	'Anvi konnen plis':'Know more',
	"Enskri nan yon bon lekol":"Find a good school",
	'Jere e administrate yon lekol':"Manage a school",
	'Jwenn yon lekol pou timoun nan enskri byen rapid san deplasman':"Find a school for your child, fast and free",
	'Ou se yon enkoni oubyen modpas la pa mache':'Unkonown user or invalid password',
	'Imel ou Nimewo telefon':'Email or phone number',
	'Modpas':"Password",
	"kite sesyon an aktive":"Remember me",
	"Mwen bliye modpas mwen !":"Forgot password ?",
	"Si'w pa ko manb":"Not a member ?",
	"Enskri gratis":"Sign up free",
	"Tout chan yo obligatwa":"All field required",
	'Retape modpas la':"Confirm the password",
	"Enskri, vle di ke ou asepte":"You agree with",
	"kondisyon itlizasyon nou yo":"Conditions manual ?",
	"Mwen li e mwen asepte":"Read and agree",
	"Enskri":"Signup",
	"Enskripsyon":"Create an account",
	'Moun ki fe pati administrasyon an se':"People part of administration",
	'Klike pou ajoute':"Click to add",
	'CIN ou NIF':'National ID',
	"Valide":"Save",
	"Anile":"Cancel",
	"Sivilite":"Status",
	"Telefon ou Imel administrate a":"Phone or email of the adminstrator",
	'Anrejistre e ajoute yon nouvo':'Save and add new',
	'Anrejistre e fini':'Save and finish',
	'Etap swivan':'Next step',
	'Etape':"Step",
	"jwenn travay nan yon lekol":"Get a job",
	"Plis ke kalite nou baw pou, konsilte done lekol, jwenn yon djob ou fe jesyon dosye elev, Eske'w pre pouw dekouvri anpil lot fonksyonalite pisan ke nou ofri 'w?": "More quality, we help you to view data in school, obtain employment or student records management. Are you ready to discover many other powerful features we offer?",
	"Chwazi youn nan 3 ongle anle yo pouw komanse":"Choose one of three widgets above to start",
	"Tout dwa rezeve":"Copyright ",
	"De nou menm":"About us",
	"Oganizasyon dirije pa Code9Haiti":"Organisation directed by Code9Haiti",
	"Lekol mwen yo":"My schools",
	"Direkte":"Director",
	'Adres':"Adress",
	"Dekonekte e kite lekol la":"Log out and leave school",
	"Sevi ak sit sa a, pou'w arive jwenn yon bon lekol pou'w enskri timoun ou yo. Chache e twouve meye lekol la, an sa ki pou we ak: Pefomans, kantite lajan, lokalite e plis anko":"Finding a good school for your children, look for the best in terms :: Performance, Cost, Location etc ...",
	"Jere dosye elev, pwofese ak manm nan administrsyon yo byen fasil. Ak yon entefas klasik, wap kapab mete elev, paran e pwofese o kouran de tout sa kap pase lekol la,  e plis anko":"Gérer les dossiers des élèves, enseignants et membres de l'administration devient tres facile. Avec une interface classique, alertez-les par sms, email ..., et plus encore",
	"Ou kapap vizyone tout lekol ki ap chache pwofese, administrate e lot anko, pou travay. Voye CV ak let motivasyon byen rapid san deplasman":"Faites des recherches de boulots dans les ecoles. Envoyez votre CV et lettre de motivation rapide et sans de deplacement",
	"Paj Enskripsyon Lekol":"School registration",
	"Enfomasyon sou lekol la":"About the school",
	"Eske se ou ki direkte lekol sa":"Are you the director",
	"Wi":"Yes",
	"Non lekol la":"Name of school",
	"Kòd idantifikasyon lekol la":"ID Code of school",
	"Tanpri tape yon kod valid, pou evite ere":"Please, type a valid ID",
	"Adres lekol la":"Place of the school",
	"Ki komin": "What city",
	"Telefon":"Phone",
	'Telephone':"Phone",
	"Imel":"Email",
	"Tanpri tape'l san tire, ni espas":"Svp Taper le sans tiret, ni espace",
	"Sit web":"Site Web",
	"Li ka yon blog, paj rezosoyal...":"A blog, a social page",
	"Lekol la piblik ou prive ?":"Private school or public ?",
	"Piblik":"Public",
	'Wol':'Role',
	'Prive':'Private',
	"Si lekol la gen logo":"Logo of school",
	"Chwazi yon imaj":"Browse an image",
	"Anrejistre e pase a etap apre":"Save and next",
	"Tounen nan paj akey":"Back to home",
	"Ajoute enfomasyon moun ki direkte lekol la":"About the director",
	'Anrejistre tout matye pou chak klas':"Include materiels for each grade",
	"Siyati":"Last name",
	'Pwofese yo se':"Teachers are",
	'Imel pwofese a':'Email of the teacher',
	'CIN ou NIF pwofese a':'National ID of the teacher',
	'Telefon pwofese a':"Phone number of the teacher",
	"Pwofesè yo se":"Teachers are",
	"Anrejistreman matyè pou chak nivo":"Matter for each grade",
	"Non":"First name",
	"Non-":"No",
	'Obligatwa':'Required',
	"Telefon":"Phone numer",
	"Imel":"Email",
	'Prezante kou':'About course',
	"Progresyon kou":'PErformance of course',
	"Lekol m'ap travay":"Schools",
	"Dosye elev yo":"Records of students",
	"Pefomans klas yo":"Class performance",
	"Not ak bilten":"Notes and bulletin",
	'Tach mwen':"To do",
	"Dokiman pedagojik":"Pedagogical materiels",
	"Albom foto pwomosyon":"Photo album",
	"Tach pwofese yo":"Teachers tasks",
	"Pwogram anyel":"Annual program",
	"Pibliye yon aktivite":"Share an activity",
	"Konfigirasyon":"Settings",
	"TABLO":"BOARD",
	"Chache":"Search",
	"Mesajeri":"Message",
	"Ajanda":"Diary",
	"Pefomans":"Performance",
	"Anons":"Announcement",
	"ISTORIK":"HISTORIC",
	"MESAJRI":"MESSAGE",
	"Voye ale":"Send",
	"Sal de klas":"Classroom",
	"Resous":"Resource",
	"Rapo":"Report",
	"Kod":"Code",
	'Moun ki fe kou a':'Author of the course',
	"Seks":"Gender",
	'Bay tout lekol la':'To school member',
	'Bay tout paran yo':'To all parents',
	'Bay tout pwofese yo':'To all teachers',
	'Prezans':"Presence",
	"Bilten":"Report",
	"Pefomans":"Rating",
	"N'ap fasilite'w jwenn yon djob":"On Vous Facilite la tache d'emploie",
	"Jwenn travay nan kelke lekol ki ap chache swa Pwofese ou Administrate pi fasil...":"Trouver des emploie de ",
	"Li enpotan pou'w ta kite enfomasyon sou ou":"Important de laisser quelque information sur toi",
	'Pefomans akademik de':'Academic performance of',
	"Anrejistre'l":"Save",
	'Griy pwogresyon':"Progression grid",
	'Griy prezantasyon kou':"Course presentation grid",
	"Sa pa anpeche'w we ki lekol kap rekrite moun pou pos pwofese ou administrate. Si'w gen yon CV ou ka metel sou platfom nan. Si'w pa genyen, nap pemet ou eksplwate tout eksperyans nou yo pou'n ede'w nan etap sila a.":"Cela n'empeche pas de voir celui qui recruite des professeurs ou administrateurs. Si vous avez un CV, Mets le sur cette platform. Dans le cas contraire on vous permettera d'exploiter toutes les experiences",
	"Kreye CV mwen":"Creatiing a curriculum",
	'Fe rechech':'Search',
	'Chache':"Go",
	'Mizantren':'Warm up',
	'Dekouvet':'Discovery',
	'Fiksasyon':"Fixation",
	'Evalyasyon':"Evaluation",
	"Pwogram anyel lekol la":"Annual program of the school",
	'Prezan':"Present",
	'Absan':"Absent",
	'Fe rechech':'Search',
	'Objektif':"Goal",
	'Devwa baze sou':'Homework',
	'Matye':"Course",
	'Tem devlope':"Talked about",
	'Obsevasyon direksyon an':'Lead observations',
	'Sa direksyon an konstate de sa':'What do the director think about',
	"Enskri yon timoun":"Enroll a student",
	"Direkte":"Director",
	"Nivo":"Level",
	"Nonb adminstrate":"How many administrators",
	"Nonb pwofese":"How many teachers",
	"Adres":"Adress",
	'LIS LIV YO':"LIST OF MATERIALS",
	"Imel":"Email",
	"Elev":"Student",
	"Kontwol prezans elev":"Presence",
	'Ekri sms la':"Type your message",
	'Ekri imel la':"Type yor email",
	"Telefon":"Phone number",
	"Lajan antre":"Admission fees",
	"Lajan pa mwa":"Monthly cash",
	"LIS LIV KLAS YO":"Lists of school books",
	"Lekol sa ap chache yon pwofese pou rekritman":"The school is looking for teachers",
	"Lese yon mesaj":"Leave a message",
	"Postile pou pos la":"Apply",
	"Siw vle fe demand enskripsyon pou yon timoun klike sou":"For an application for registration, click on ",
	"STATISTIK":"STATISTIC",
	"DIKSYONE":'DICTIONARY',
	"Reyisi":"Succeed",
	"Reyisit":"Success",
	"Konnen plis":"Know more",
	"Move pant":"Poor",
	"Medyok":"Very bad",
	'Idantifye sou nimewo':"ID Number",
	"M'ap kreye paj lekol mwen":"I create my own school page",
	"Chache":"Go"
}

@register.filter
def trans(txt,lg_ch="HT"):
	if lg_ch == "FR":
		rep = FR_DICT.get(txt.capitalize())
		if not rep:
			rep = FR_DICT.get(txt.title())
		if not rep:
			rep = FR_DICT.get(txt.capitalize())
		if not rep:
			rep = txt
		return rep
	elif lg_ch == "EN":
		rep = EN_DICT.get(txt.capitalize())
		if not rep:
			rep = EN_DICT.get(txt.title())
		if not rep:
			rep = EN_DICT.get(txt.capitalize())
		if not rep:
			rep = txt
		return rep
	else:
		if txt.capitalize() == "No-":
			return txt.replace("-","")
		return txt

@register.filter
def genre(txt,desc=None):
	D = {'c':'que'}

	rep = FR_DICT.get(txt.capitalize())
	if not rep:
		rep = FR_DICT.get(txt.title())
	if not rep:
		rep = FR_DICT.get(txt.capitalize())
	if not rep:
		rep = txt

	if type(txt) == 'str':
		if not desc:
			return rep+"e"
		else:
			return rep[:-len(desc)]
	return txt

@register.filter
def concat(obj,scnd):
	return str(obj)+str(scnd)

@register.filter
def string(obj):
	return str(obj)

@register.filter
def order_by(obj,item):
	try:
		return obj.order_by(item)
	except:
		return obj