# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 02:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import index.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=index.models.NOW)),
                ('date_modified', models.DateTimeField(default=index.models.NOW)),
                ('slug', models.SlugField(blank=True)),
                ('code', models.CharField(max_length=14)),
                ('photo', models.ImageField(blank=True, upload_to='profile_photo/%d-%m-%Y/')),
                ('phone', models.CharField(blank=True, max_length=22)),
                ('national_id', models.CharField(blank=True, max_length=18)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin'), ('A', 'Autres')], default='M', max_length=50)),
                ('activation_key', models.CharField(blank=True, max_length=255)),
                ('default_password', models.CharField(blank=True, max_length=200)),
                ('date_key_expired', models.DateTimeField(blank=True, null=True)),
                ('is_password_changed', models.BooleanField(default=True)),
                ('date_password_changed', models.DateTimeField(blank=True, null=True)),
                ('is_account_confirmed', models.BooleanField(default=False)),
                ('date_account_confirmed', models.DateTimeField(blank=True, null=True)),
                ('language', models.CharField(choices=[('FR', 'French'), ('EN', 'English')], default='EN', max_length=2)),
                ('nb_send_email', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='get_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('is_user_only', 'Access as User Only'),),
            },
        ),
    ]
